import type { ComponentDefinition } from "@/types/lesson"

export const componentDefinitions: ComponentDefinition[] = [
  // Content Components
  {
    type: "paragraph",
    label: "Paragraph",
    category: "content",
    description: "Text block with formatting...",
    icon: "📝",
    defaultProps: {
      content: "Enter your text here...",
      align: "left",
    },
    propDefinitions: [
      {
        name: "content",
        label: "Content",
        type: "richText",
        required: true,
        defaultValue: "Enter your text here...",
      },
      {
        name: "align",
        label: "Alignment",
        type: "select",
        required: false,
        defaultValue: "left",
        options: [
          { label: "Left", value: "left" },
          { label: "Center", value: "center" },
          { label: "Right", value: "right" },
          { label: "Justify", value: "justify" },
        ],
      },
    ],
  },
  {
    type: "heading",
    label: "Heading",
    category: "content",
    description: "Section title or subtitle...",
    icon: "📌",
    defaultProps: {
      content: "Heading Text",
      level: 2,
      align: "left",
    },
    propDefinitions: [
      {
        name: "content",
        label: "Content",
        type: "string",
        required: true,
        defaultValue: "Heading Text",
      },
      {
        name: "level",
        label: "Heading Level",
        type: "select",
        required: true,
        defaultValue: 2,
        options: [
          { label: "H1 (Largest)", value: 1 },
          { label: "H2", value: 2 },
          { label: "H3", value: 3 },
          { label: "H4", value: 4 },
          { label: "H5", value: 5 },
          { label: "H6 (Smallest)", value: 6 },
        ],
      },
      {
        name: "align",
        label: "Alignment",
        type: "select",
        required: false,
        defaultValue: "left",
        options: [
          { label: "Left", value: "left" },
          { label: "Center", value: "center" },
          { label: "Right", value: "right" },
        ],
      },
    ],
  },
  {
    type: "bulletList",
    label: "Bullet List",
    category: "content",
    description: "Ordered or unordered list...",
    icon: "📋",
    defaultProps: {
      items: ["Item 1", "Item 2", "Item 3"],
      type: "unordered",
    },
    propDefinitions: [
      {
        name: "items",
        label: "List Items",
        type: "componentArray",
        required: true,
        defaultValue: ["Item 1", "Item 2", "Item 3"],
      },
      {
        name: "type",
        label: "List Type",
        type: "select",
        required: true,
        defaultValue: "unordered",
        options: [
          { label: "Unordered (Bullets)", value: "unordered" },
          { label: "Ordered (Numbers)", value: "ordered" },
        ],
      },
    ],
  },
  {
    type: "table",
    label: "Table",
    category: "content",
    description: "Organize data in rows and columns...",
    icon: "📊",
    defaultProps: {
      rows: 2,
      columns: 2,
      data: [
        ["Cell 1", "Cell 2"],
        ["Cell 3", "Cell 4"],
      ],
    },
    propDefinitions: [
      {
        name: "rows",
        label: "Number of Rows",
        type: "number",
        required: true,
        defaultValue: 2,
        min: 1,
        max: 10,
      },
      {
        name: "columns",
        label: "Number of Columns",
        type: "number",
        required: true,
        defaultValue: 2,
        min: 1,
        max: 10,
      },
      {
        name: "data",
        label: "Table Data",
        type: "componentArray",
        required: true,
        defaultValue: [
          ["Cell 1", "Cell 2"],
          ["Cell 3", "Cell 4"],
        ],
      },
    ],
  },
  {
    type: "image",
    label: "Image",
    category: "content",
    description: "Display image with caption...",
    icon: "🖼️",
    defaultProps: {
      src: "/placeholder.svg?height=300&width=400",
      alt: "Image description",
      caption: "",
      width: "100%",
    },
    propDefinitions: [
      {
        name: "src",
        label: "Image Source",
        type: "image",
        required: true,
        defaultValue: "/placeholder.svg?height=300&width=400",
      },
      {
        name: "alt",
        label: "Alt Text",
        type: "string",
        required: true,
        defaultValue: "Image description",
      },
      {
        name: "caption",
        label: "Caption",
        type: "string",
        required: false,
        defaultValue: "",
      },
      {
        name: "width",
        label: "Width",
        type: "string",
        required: false,
        defaultValue: "100%",
      },
    ],
  },
  {
    type: "video",
    label: "Video",
    category: "content",
    description: "Embed video from URL...",
    icon: "🎥",
    defaultProps: {
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      caption: "",
      aspectRatio: "16:9",
      autoPlay: false,
    },
    propDefinitions: [
      {
        name: "url",
        label: "YouTube Video URL / Link",
        type: "string",
        required: true,
        placeholder: "https://www.youtube.com/watch?v=...",
        description: "Paste a YouTube watch link or share URL",
        defaultValue: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      },
      {
        name: "caption",
        label: "Video Caption",
        type: "string",
        required: false,
        placeholder: "Optional video description",
        defaultValue: "",
      },
      {
        name: "aspectRatio",
        label: "Aspect Ratio",
        type: "select",
        required: false,
        defaultValue: "16:9",
        options: [
          { label: "Widescreen (16:9)", value: "16:9" },
          { label: "Standard (4:3)", value: "4:3" },
          { label: "Square (1:1)", value: "1:1" },
        ],
      },
      {
        name: "autoPlay",
        label: "Autoplay Video",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
    ],
  },

  // Interactive Components
  {
    type: "quiz",
    label: "Quiz",
    category: "interactive",
    description: "Multiple choice questions...",
    icon: "❓",
    defaultProps: {
      questions: [
        {
          id: "q1",
          question: "What is the capital of France?",
          options: [
            { id: "1", text: "London", isCorrect: false },
            { id: "2", text: "Paris", isCorrect: true },
            { id: "3", text: "Berlin", isCorrect: false },
            { id: "4", text: "Madrid", isCorrect: false },
          ],
          explanation: "Paris is the capital and most populous city of France.",
        },
      ],
      showExplanation: true,
      shuffleOptions: true,
      randomizeAnswers: true,
      points: 10,
      mode: "practice",
      state: "active",
      status: "uncompleted"
    },
    propDefinitions: [
      {
        name: "questions",
        label: "Questions",
        type: "componentArray",
        required: true,
        defaultValue: [
          {
            id: "q1",
            question: "What is the capital of France?",
            options: [
              { id: "1", text: "London", isCorrect: false },
              { id: "2", text: "Paris", isCorrect: true },
              { id: "3", text: "Berlin", isCorrect: false },
              { id: "4", text: "Madrid", isCorrect: false },
            ],
            explanation: "Paris is the capital and most populous city of France.",
          },
        ],
      },
      {
        name: "showExplanation",
        label: "Show Explanation",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "shuffleOptions",
        label: "Randomize Answers / Options",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "points",
        label: "Points Per Question",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: false,
        defaultValue: "uncompleted",
        options: [
          { label: "Uncompleted", value: "uncompleted" },
          { label: "Complete", value: "complete" }
        ]
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 5,
        max: 300,
      },
    ],
  },
  {
    type: "dragDrop",
    label: "Drag & Drop",
    category: "interactive",
    description: "Match items by dragging...",
    icon: "🎯",
    defaultProps: {
      title: "Arrange in the correct order",
      items: [
        { id: "1", text: "First item", correctIndex: 0 },
        { id: "2", text: "Second item", correctIndex: 1 },
        { id: "3", text: "Third item", correctIndex: 2 },
      ],
      shuffled: true,
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Arrange in the correct order",
      },
      {
        name: "items",
        label: "Items",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", text: "First item", correctIndex: 0 },
          { id: "2", text: "Second item", correctIndex: 1 },
          { id: "3", text: "Third item", correctIndex: 2 },
        ],
      },
      {
        name: "shuffled",
        label: "Shuffle Items",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 5,
        max: 300,
      },
    ],
  },
  {
    type: "matchingPairs",
    label: "Matching Pairs",
    category: "interactive",
    description: "Match related items...",
    icon: "🔄",
    defaultProps: {
      title: "Match the items",
      pairs: [
        { id: "1", left: "Dog", right: "Bark" },
        { id: "2", left: "Cat", right: "Meow" },
        { id: "3", left: "Cow", right: "Moo" },
      ],
      shuffled: true,
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Match the items",
      },
      {
        name: "pairs",
        label: "Matching Pairs",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", left: "Dog", right: "Bark" },
          { id: "2", left: "Cat", right: "Meow" },
          { id: "3", left: "Cow", right: "Moo" },
        ],
      },
      {
        name: "shuffled",
        label: "Shuffle Items",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 5,
        max: 300,
      },
    ],
  },
  {
    type: "fillInTheBlank",
    label: "Fill in Blank",
    category: "interactive",
    description: "Complete missing words...",
    icon: "✏️",
    defaultProps: {
      title: "Fill in the blanks",
      text: "The capital of France is {{blank}} and the capital of Japan is {{blank}}.",
      blanks: [
        { id: "b1", answer: "Paris", alternatives: ["paris"] },
        { id: "b2", answer: "Tokyo", alternatives: ["tokyo"] },
      ],
      caseSensitive: false,
      points: 10,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Fill in the blanks",
      },
      {
        name: "text",
        label: "Text with Blanks",
        type: "string",
        required: true,
        defaultValue: "The capital of France is {{blank}} and the capital of Japan is {{blank}}.",
      },
      {
        name: "blanks",
        label: "Blanks",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "b1", answer: "Paris", alternatives: ["paris"] },
          { id: "b2", answer: "Tokyo", alternatives: ["tokyo"] },
        ],
      },
      {
        name: "caseSensitive",
        label: "Case Sensitive",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
    ],
  },
  {
    type: "flashcards",
    label: "Flashcards",
    category: "interactive",
    description: "Two-sided study cards...",
    icon: "🎴",
    defaultProps: {
      title: "Flashcards",
      cards: [
        { id: "1", front: "What is the capital of France?", back: "Paris" },
        { id: "2", front: "What is the capital of Japan?", back: "Tokyo" },
        { id: "3", front: "What is the capital of Australia?", back: "Canberra" },
      ],
      mode: "practice",
      state: "active"
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Flashcards",
      },
      {
        name: "cards",
        label: "Flashcards",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", front: "What is the capital of France?", back: "Paris" },
          { id: "2", front: "What is the capital of Japan?", back: "Tokyo" },
          { id: "3", front: "What is the capital of Australia?", back: "Canberra" },
        ],
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
    ],
  },
  {
    type: "codeEditor",
    label: "Code Editor",
    category: "interactive",
    description: "Write and test code...",
    icon: "👨‍💻",
    defaultProps: {
      title: "Code Editor",
      initialCode: "// Write your code here\nconsole.log('Hello, world!');",
      language: "javascript",
      readOnly: false,
      testCases: [
        {
          id: "test1",
          input: "",
          expectedOutput: "Hello, world!",
        },
      ],
      points: 10,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Code Editor",
      },
      {
        name: "initialCode",
        label: "Initial Code",
        type: "string",
        required: true,
        defaultValue: "// Write your code here\nconsole.log('Hello, world!');",
      },
      {
        name: "language",
        label: "Programming Language",
        type: "select",
        required: true,
        defaultValue: "javascript",
        options: [
          { label: "JavaScript", value: "javascript" },
          { label: "Python", value: "python" },
          { label: "Java", value: "java" },
          { label: "C#", value: "csharp" },
        ],
      },
      {
        name: "readOnly",
        label: "Read Only",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
      {
        name: "testCases",
        label: "Test Cases",
        type: "componentArray",
        required: false,
        defaultValue: [
          {
            id: "test1",
            input: "",
            expectedOutput: "Hello, world!",
          },
        ],
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
    ],
  },
  {
    type: "hotspot",
    label: "Hotspot",
    category: "interactive",
    description: "Clickable image regions...",
    icon: "🎯",
    defaultProps: {
      title: "Interactive Image",
      image: "/placeholder.svg?height=400&width=600",
      hotspots: [
        { id: "1", x: 0.3, y: 0.4, label: "Point 1", content: "This is the first point of interest" },
        { id: "2", x: 0.7, y: 0.6, label: "Point 2", content: "This is the second point of interest" },
      ],
      mode: "practice",
      state: "active",
      behavior: "quiz", // "discovery" | "quiz"
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Interactive Image",
      },
      {
        name: "image",
        label: "Image",
        type: "image",
        required: true,
        defaultValue: "/placeholder.svg?height=400&width=600",
      },
      {
        name: "hotspots",
        label: "Hotspots",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", x: 0.3, y: 0.4, label: "Point 1", content: "This is the first point of interest" },
          { id: "2", x: 0.7, y: 0.6, label: "Point 2", content: "This is the second point of interest" },
        ],
      },
      {
        name: "behavior",
        label: "Interaction Behavior",
        type: "select",
        required: true,
        defaultValue: "quiz",
        options: [
          { label: "Discovery (Information only)", value: "discovery" },
          { label: "Quiz (Find all to complete)", value: "quiz" },
        ],
      },
      {
        name: "showNumbers",
        label: "Show Pin Numbers in Explore Mode",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
    ],
  },

  // Gamified Components
  {
    type: "poll",
    label: "Poll",
    category: "interactive",
    description: "Interactive opinion poll with live response tallies and animated percentage bars.",
    icon: "📊",
    defaultProps: {
      question: "Which state of matter has a fixed shape and volume?",
      options: [
        { id: "opt1", text: "Solid" },
        { id: "opt2", text: "Liquid" },
        { id: "opt3", text: "Gas" },
        { id: "opt4", text: "Plasma" },
      ],
      points: 5,
    },
    propDefinitions: [
      {
        name: "question",
        label: "Poll Question",
        type: "string",
        required: true,
        defaultValue: "Which state of matter has a fixed shape and volume?",
      },
      {
        name: "options",
        label: "Poll Options",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "opt1", text: "Solid" },
          { id: "opt2", text: "Liquid" },
          { id: "opt3", text: "Gas" },
          { id: "opt4", text: "Plasma" },
        ],
      },
      {
        name: "points",
        label: "Participation Points",
        type: "number",
        required: false,
        defaultValue: 5,
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
    ],
  },
  {
    type: "flashcardQuiz",
    label: "Flashcard Quiz",
    category: "interactive",
    description: "Multi-question quiz where the question flips onto a card, then answer options flip in sequentially for the student to pick.",
    icon: "🎴",
    defaultProps: {
      questions: [
        {
          id: "fq1",
          question: "What is the capital of France?",
          options: ["Paris", "London", "Berlin", "Madrid"],
          correctAnswer: 0,
        },
        {
          id: "fq2",
          question: "What is 7 × 8?",
          options: ["54", "56", "63", "64"],
          correctAnswer: 1,
        },
      ],
      points: 20,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "questions",
        label: "Questions",
        type: "componentArray",
        required: true,
        defaultValue: [
          {
            id: "fq1",
            question: "What is the capital of France?",
            options: ["Paris", "London", "Berlin", "Madrid"],
            correctAnswer: 0,
          },
        ],
      },
      {
        name: "points",
        label: "Total Points",
        type: "number",
        required: false,
        defaultValue: 20,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice", value: "practice" },
          { label: "Live", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
    ],
  },
  {
    type: "multiSelectQuiz",
    label: "Multi-Select Quiz",
    category: "interactive",
    description: "Quiz where students select ALL correct answers from colorful option cards, with partial-score feedback.",
    icon: "☑️",
    defaultProps: {
      title: "Select All That Apply",
      questions: [
        {
          id: "q1",
          question: "Which of the following are mammals?",
          options: [
            { id: "a", text: "Dog", isCorrect: true, color: "bg-violet-500" },
            { id: "b", text: "Eagle", isCorrect: false, color: "bg-amber-500" },
            { id: "c", text: "Whale", isCorrect: true, color: "bg-sky-500" },
            { id: "d", text: "Salmon", isCorrect: false, color: "bg-rose-500" },
          ],
        },
      ],
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Quiz Title",
        type: "string",
        required: false,
        defaultValue: "Select All That Apply",
      },
      {
        name: "questions",
        label: "Questions",
        type: "componentArray",
        required: true,
        defaultValue: [],
      },
      {
        name: "points",
        label: "Total Points",
        type: "number",
        required: false,
        defaultValue: 15,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice", value: "practice" },
          { label: "Live", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
    ],
  },

  // Structure Components
  {
    type: "slideTitle",
    label: "Slide Title",
    category: "structure",
    description: "Main slide heading...",
    icon: "📑",
    defaultProps: {
      content: "Slide Title",
      align: "center",
      color: "black",
      backgroundColor: "transparent",
    },
    propDefinitions: [
      {
        name: "content",
        label: "Title Content",
        type: "string",
        required: true,
        defaultValue: "Slide Title",
      },
      {
        name: "align",
        label: "Text Alignment",
        type: "select",
        required: false,
        defaultValue: "center",
        options: [
          { label: "Left", value: "left" },
          { label: "Center", value: "center" },
          { label: "Right", value: "right" },
        ],
      },
      {
        name: "color",
        label: "Text Color",
        type: "color",
        required: false,
        defaultValue: "black",
      },
      {
        name: "backgroundColor",
        label: "Background Color",
        type: "color",
        required: false,
        defaultValue: "transparent",
      },
    ],
  },
]
