import type { ComponentDefinition } from "@/types/lesson"
import { DEFAULT_WHEEL_QUESTIONS } from "@/lib/spin-the-wheel-utils"

export const componentDefinitions: ComponentDefinition[] = [
  // Content Components
  {
    type: "paragraph",
    label: "Paragraph",
    category: "content",
    description: "Text block with formatting...",
    icon: "📝",
    defaultProps: {
      content: "Enter your text here...",
      align: "left",
      audioUrl: "",
      autoPlayAudio: false,
    },
    propDefinitions: [
      {
        name: "content",
        label: "Content",
        type: "richText",
        required: true,
        defaultValue: "Enter your text here...",
      },
      {
        name: "align",
        label: "Alignment",
        type: "select",
        required: false,
        defaultValue: "left",
        options: [
          { label: "Left", value: "left" },
          { label: "Center", value: "center" },
          { label: "Right", value: "right" },
          { label: "Justify", value: "justify" },
        ],
      },
      {
        name: "audioUrl",
        label: "Audio Track URL",
        type: "audio",
        required: false,
        defaultValue: "",
      },
      {
        name: "autoPlayAudio",
        label: "Auto-Play Audio",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
    ],
  },
  {
    type: "heading",
    label: "Heading",
    category: "content",
    description: "Section title or subtitle...",
    icon: "📌",
    defaultProps: {
      content: "Heading Text",
      level: 2,
      align: "left",
    },
    propDefinitions: [
      {
        name: "content",
        label: "Content",
        type: "string",
        required: true,
        defaultValue: "Heading Text",
      },
      {
        name: "level",
        label: "Heading Level",
        type: "select",
        required: true,
        defaultValue: 2,
        options: [
          { label: "H1 (Largest)", value: 1 },
          { label: "H2", value: 2 },
          { label: "H3", value: 3 },
          { label: "H4", value: 4 },
          { label: "H5", value: 5 },
          { label: "H6 (Smallest)", value: 6 },
        ],
      },
      {
        name: "align",
        label: "Alignment",
        type: "select",
        required: false,
        defaultValue: "left",
        options: [
          { label: "Left", value: "left" },
          { label: "Center", value: "center" },
          { label: "Right", value: "right" },
        ],
      },
    ],
  },
  {
    type: "bulletList",
    label: "Bullet List",
    category: "content",
    description: "Ordered or unordered list...",
    icon: "📋",
    defaultProps: {
      items: ["Item 1", "Item 2", "Item 3"],
      type: "unordered",
      audioUrl: "",
      autoPlayAudio: false,
    },
    propDefinitions: [
      {
        name: "items",
        label: "List Items",
        type: "componentArray",
        required: true,
        defaultValue: ["Item 1", "Item 2", "Item 3"],
      },
      {
        name: "type",
        label: "List Type",
        type: "select",
        required: true,
        defaultValue: "unordered",
        options: [
          { label: "Unordered (Bullets)", value: "unordered" },
          { label: "Ordered (Numbers)", value: "ordered" },
        ],
      },
      {
        name: "audioUrl",
        label: "Audio Track URL",
        type: "audio",
        required: false,
        defaultValue: "",
      },
      {
        name: "autoPlayAudio",
        label: "Auto-Play Audio",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
    ],
  },
  {
    type: "table",
    label: "Table",
    category: "content",
    description: "Organize data in rows and columns...",
    icon: "📊",
    defaultProps: {
      rows: 2,
      columns: 2,
      data: [
        ["Cell 1", "Cell 2"],
        ["Cell 3", "Cell 4"],
      ],
    },
    propDefinitions: [
      {
        name: "rows",
        label: "Number of Rows",
        type: "number",
        required: true,
        defaultValue: 2,
        min: 1,
        max: 10,
      },
      {
        name: "columns",
        label: "Number of Columns",
        type: "number",
        required: true,
        defaultValue: 2,
        min: 1,
        max: 10,
      },
      {
        name: "data",
        label: "Table Data",
        type: "componentArray",
        required: true,
        defaultValue: [
          ["Cell 1", "Cell 2"],
          ["Cell 3", "Cell 4"],
        ],
      },
    ],
  },
  {
    type: "image",
    label: "Image",
    category: "content",
    description: "Display image with caption...",
    icon: "🖼️",
    defaultProps: {
      src: "/placeholder.svg?height=300&width=400",
      alt: "Image description",
      caption: "",
      width: "100%",
    },
    propDefinitions: [
      {
        name: "src",
        label: "Image Source",
        type: "image",
        required: true,
        defaultValue: "/placeholder.svg?height=300&width=400",
      },
      {
        name: "alt",
        label: "Alt Text",
        type: "string",
        required: true,
        defaultValue: "Image description",
      },
      {
        name: "caption",
        label: "Caption",
        type: "string",
        required: false,
        defaultValue: "",
      },
      {
        name: "width",
        label: "Width",
        type: "string",
        required: false,
        defaultValue: "100%",
      },
    ],
  },
  {
    type: "callout",
    label: "Callout Box",
    category: "content",
    description: "Highlighted alert box for notes, tips, warnings, and key takeaways.",
    icon: "💡",
    defaultProps: {
      variant: "note",
      title: "Important Note",
      content: "Add key insights, warnings, or tips here...",
    },
    propDefinitions: [
      {
        name: "variant",
        label: "Variant",
        type: "select",
        required: true,
        defaultValue: "note",
        options: [
          { label: "Note (Blue)", value: "note" },
          { label: "Tip (Green)", value: "tip" },
          { label: "Warning (Yellow)", value: "warning" },
          { label: "Important (Red)", value: "important" },
        ],
      },
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Important Note",
      },
      {
        name: "content",
        label: "Content",
        type: "richText",
        required: true,
        defaultValue: "Add key insights, warnings, or tips here...",
      },
    ],
  },
  {
    type: "accordion",
    label: "Accordion FAQ",
    category: "content",
    description: "Collapsible expandable panels for glossaries and FAQ lists.",
    icon: "📂",
    defaultProps: {
      title: "Key Definitions",
      items: [
        { id: "acc-1", title: "What is this concept?", content: "Detailed explanation goes here.", audioUrl: "" },
        { id: "acc-2", title: "Why is it important?", content: "Key significance and context.", audioUrl: "" },
      ],
      allowMultiple: false,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Accordion Section Title",
        type: "string",
        required: false,
        defaultValue: "Key Definitions",
      },
      {
        name: "items",
        label: "Accordion Panels",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "acc-1", title: "What is this concept?", content: "Detailed explanation goes here.", audioUrl: "" },
        ],
      },
      {
        name: "allowMultiple",
        label: "Allow Multiple Open",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
    ],
  },
  {
    type: "quote",
    label: "Quote Card",
    category: "content",
    description: "Featured quote box with author attribution and tactile styling.",
    icon: "💬",
    defaultProps: {
      text: "Learning is a treasure that will follow its owner everywhere.",
      author: "Chinese Proverb",
      source: "Ancient Wisdom",
    },
    propDefinitions: [
      {
        name: "text",
        label: "Quote Text",
        type: "richText",
        required: true,
        defaultValue: "Learning is a treasure that will follow its owner everywhere.",
      },
      {
        name: "author",
        label: "Author Name",
        type: "string",
        required: false,
        defaultValue: "Chinese Proverb",
      },
      {
        name: "source",
        label: "Source / Context",
        type: "string",
        required: false,
        defaultValue: "Ancient Wisdom",
      },
    ],
  },
  {
    type: "trueFalse",
    label: "True or False",
    category: "interactive",
    description: "Rapid-fire binary question with animated selection cards.",
    icon: "⚡",
    defaultProps: {
      statement: "The earth revolves around the sun.",
      isTrue: true,
      explanation: "Earth takes 365.25 days to complete an orbit around the Sun.",
      points: 10,
    },
    propDefinitions: [
      {
        name: "statement",
        label: "Statement",
        type: "string",
        required: true,
        defaultValue: "The earth revolves around the sun.",
      },
      {
        name: "isTrue",
        label: "Correct Answer",
        type: "boolean",
        required: true,
        defaultValue: true,
      },
      {
        name: "explanation",
        label: "Explanation",
        type: "string",
        required: false,
        defaultValue: "",
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
      },
    ],
  },
  {
    type: "video",
    label: "Video",
    category: "content",
    description: "Embed video from URL...",
    icon: "🎥",
    defaultProps: {
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      caption: "",
      aspectRatio: "16:9",
      autoPlay: false,
      poster: "",
    },
    propDefinitions: [
      {
        name: "url",
        label: "YouTube Video URL / Link",
        type: "string",
        required: true,
        placeholder: "https://www.youtube.com/watch?v=...",
        description: "Paste a YouTube watch link or share URL",
        defaultValue: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      },
      {
        name: "caption",
        label: "Video Caption",
        type: "string",
        required: false,
        placeholder: "Optional video description",
        defaultValue: "",
      },
      {
        name: "aspectRatio",
        label: "Aspect Ratio",
        type: "select",
        required: false,
        defaultValue: "16:9",
        options: [
          { label: "Widescreen (16:9)", value: "16:9" },
          { label: "Standard (4:3)", value: "4:3" },
          { label: "Square (1:1)", value: "1:1" },
        ],
      },
      {
        name: "autoPlay",
        label: "Autoplay Video",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
      {
        name: "poster",
        label: "Poster Frame Image URL",
        type: "image",
        required: false,
        defaultValue: "",
        description: "Custom video preview thumbnail image",
      },
    ],
  },

  // Interactive Components
  {
    type: "quiz",
    label: "Quiz",
    category: "interactive",
    description: "Multiple choice questions...",
    icon: "❓",
    defaultProps: {
      questions: [
        {
          id: "q1",
          question: "What is the capital of France?",
          options: [
            { id: "1", text: "London", isCorrect: false },
            { id: "2", text: "Paris", isCorrect: true },
            { id: "3", text: "Berlin", isCorrect: false },
            { id: "4", text: "Madrid", isCorrect: false },
          ],
          explanation: "Paris is the capital and most populous city of France.",
        },
      ],
      showExplanation: true,
      shuffleOptions: true,
      randomizeAnswers: true,
      points: 10,
      mode: "practice",
      state: "active",
      status: "uncompleted"
    },
    propDefinitions: [
      {
        name: "questions",
        label: "Questions",
        type: "componentArray",
        required: true,
        defaultValue: [
          {
            id: "q1",
            question: "What is the capital of France?",
            options: [
              { id: "1", text: "London", isCorrect: false },
              { id: "2", text: "Paris", isCorrect: true },
              { id: "3", text: "Berlin", isCorrect: false },
              { id: "4", text: "Madrid", isCorrect: false },
            ],
            explanation: "Paris is the capital and most populous city of France.",
          },
        ],
      },
      {
        name: "showExplanation",
        label: "Show Explanation",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "shuffleOptions",
        label: "Randomize Answers / Options",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "points",
        label: "Points Per Question",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: false,
        defaultValue: "uncompleted",
        options: [
          { label: "Uncompleted", value: "uncompleted" },
          { label: "Complete", value: "complete" }
        ]
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 5,
        max: 300,
      },
    ],
  },
  {
    type: "dragDrop",
    label: "Drag & Drop",
    category: "interactive",
    description: "Match items by dragging...",
    icon: "🎯",
    defaultProps: {
      title: "Arrange in the correct order",
      items: [
        { id: "1", text: "First item", correctIndex: 0 },
        { id: "2", text: "Second item", correctIndex: 1 },
        { id: "3", text: "Third item", correctIndex: 2 },
      ],
      shuffled: true,
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Arrange in the correct order",
      },
      {
        name: "items",
        label: "Items",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", text: "First item", correctIndex: 0 },
          { id: "2", text: "Second item", correctIndex: 1 },
          { id: "3", text: "Third item", correctIndex: 2 },
        ],
      },
      {
        name: "shuffled",
        label: "Shuffle Items",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 5,
        max: 300,
      },
    ],
  },
  {
    type: "matchingPairs",
    label: "Matching Pairs",
    category: "interactive",
    description: "Match related items...",
    icon: "🔄",
    defaultProps: {
      title: "Match the items",
      pairs: [
        { id: "1", left: "Dog", right: "Bark" },
        { id: "2", left: "Cat", right: "Meow" },
        { id: "3", left: "Cow", right: "Moo" },
      ],
      shuffled: true,
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Match the items",
      },
      {
        name: "pairs",
        label: "Matching Pairs",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", left: "Dog", right: "Bark" },
          { id: "2", left: "Cat", right: "Meow" },
          { id: "3", left: "Cow", right: "Moo" },
        ],
      },
      {
        name: "shuffled",
        label: "Shuffle Items",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 5,
        max: 300,
      },
    ],
  },
  {
    type: "fillInTheBlank",
    label: "Fill in Blank",
    category: "interactive",
    description: "Complete missing words...",
    icon: "✏️",
    defaultProps: {
      title: "Fill in the blanks",
      text: "The capital of France is {{blank}} and the capital of Japan is {{blank}}.",
      blanks: [
        { id: "b1", answer: "Paris", alternatives: ["paris"] },
        { id: "b2", answer: "Tokyo", alternatives: ["tokyo"] },
      ],
      caseSensitive: false,
      points: 10,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Fill in the blanks",
      },
      {
        name: "text",
        label: "Text with Blanks",
        type: "string",
        required: true,
        defaultValue: "The capital of France is {{blank}} and the capital of Japan is {{blank}}.",
      },
      {
        name: "blanks",
        label: "Blanks",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "b1", answer: "Paris", alternatives: ["paris"] },
          { id: "b2", answer: "Tokyo", alternatives: ["tokyo"] },
        ],
      },
      {
        name: "caseSensitive",
        label: "Case Sensitive",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 5,
        max: 300,
      },
      {
        name: "markingMode",
        label: "Marking Mode",
        type: "select",
        required: false,
        defaultValue: "self-mark",
        options: [
          { label: "Self Mark (Auto)", value: "self-mark" },
          { label: "Tutor Mark (Manual)", value: "tutor-mark" },
        ],
      },
    ],
  },
  {
    type: "shortAnswer",
    label: "Short Answer",
    category: "interactive",
    description: "Open-ended question with free-text response, keywords check, or tutor marking.",
    icon: "✍️",
    defaultProps: {
      title: "Short Answer",
      question: "Explain why ecosystems depend on primary producers:",
      placeholder: "Write your answer here...",
      correctKeywords: ["energy", "photosynthesis", "food chain"],
      markingMode: "self-mark",
      points: 10,
      mode: "practice",
      state: "active",
      timeLimit: 30,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Short Answer",
      },
      {
        name: "question",
        label: "Question Prompt",
        type: "string",
        required: true,
        defaultValue: "Explain why ecosystems depend on primary producers:",
      },
      {
        name: "placeholder",
        label: "Placeholder Text",
        type: "string",
        required: false,
        defaultValue: "Write your answer here...",
      },
      {
        name: "markingMode",
        label: "Marking Mode",
        type: "select",
        required: false,
        defaultValue: "self-mark",
        options: [
          { label: "Self Mark (Keyword Check)", value: "self-mark" },
          { label: "Tutor Mark (Manual)", value: "tutor-mark" },
        ],
      },
      {
        name: "correctKeywords",
        label: "Required Keywords (Self-Mark)",
        type: "json",
        required: false,
        defaultValue: ["energy", "photosynthesis", "food chain"],
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 30,
        min: 5,
        max: 300,
      },
    ],
  },
  {
    type: "flashcards",
    label: "Flashcards",
    category: "interactive",
    description: "Two-sided study cards...",
    icon: "🎴",
    defaultProps: {
      title: "Flashcards",
      cards: [
        { id: "1", front: "What is the capital of France?", back: "Paris" },
        { id: "2", front: "What is the capital of Japan?", back: "Tokyo" },
        { id: "3", front: "What is the capital of Australia?", back: "Canberra" },
      ],
      mode: "practice",
      state: "active",
      timeLimit: 15,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Flashcards",
      },
      {
        name: "cards",
        label: "Flashcards",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", front: "What is the capital of France?", back: "Paris" },
          { id: "2", front: "What is the capital of Japan?", back: "Tokyo" },
          { id: "3", front: "What is the capital of Australia?", back: "Canberra" },
        ],
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 5,
        max: 300,
      },
    ],
  },
  {
    type: "codeEditor",
    label: "Code Editor",
    category: "interactive",
    description: "Write and test code...",
    icon: "👨‍💻",
    defaultProps: {
      title: "Code Editor",
      initialCode: "// Write your code here\nconsole.log('Hello, world!');",
      language: "javascript",
      readOnly: false,
      testCases: [
        {
          id: "test1",
          input: "",
          expectedOutput: "Hello, world!",
        },
      ],
      points: 10,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Code Editor",
      },
      {
        name: "initialCode",
        label: "Initial Code",
        type: "string",
        required: true,
        defaultValue: "// Write your code here\nconsole.log('Hello, world!');",
      },
      {
        name: "language",
        label: "Programming Language",
        type: "select",
        required: true,
        defaultValue: "javascript",
        options: [
          { label: "JavaScript", value: "javascript" },
          { label: "Python", value: "python" },
          { label: "Java", value: "java" },
          { label: "C#", value: "csharp" },
        ],
      },
      {
        name: "readOnly",
        label: "Read Only",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
      {
        name: "testCases",
        label: "Test Cases",
        type: "componentArray",
        required: false,
        defaultValue: [
          {
            id: "test1",
            input: "",
            expectedOutput: "Hello, world!",
          },
        ],
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 30,
        min: 5,
        max: 300,
      },
    ],
  },
  {
    type: "hotspot",
    label: "Hotspot",
    category: "interactive",
    description: "Clickable image regions...",
    icon: "🎯",
    defaultProps: {
      title: "Interactive Image",
      image: "/placeholder.svg?height=400&width=600",
      hotspots: [
        { id: "1", x: 0.3, y: 0.4, label: "Point 1", content: "This is the first point of interest" },
        { id: "2", x: 0.7, y: 0.6, label: "Point 2", content: "This is the second point of interest" },
      ],
      points: 10,
      timeLimit: 15,
      mode: "practice",
      state: "active",
      behavior: "discover",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Interactive Image",
      },
      {
        name: "image",
        label: "Image",
        type: "image",
        required: true,
        defaultValue: "/placeholder.svg?height=400&width=600",
      },
      {
        name: "hotspots",
        label: "Hotspots",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", x: 0.3, y: 0.4, label: "Point 1", content: "This is the first point of interest" },
          { id: "2", x: 0.7, y: 0.6, label: "Point 2", content: "This is the second point of interest" },
        ],
      },
      {
        name: "behavior",
        label: "Interaction Behavior",
        type: "select",
        required: true,
        defaultValue: "discover",
        options: [
          { label: "Explore (Information only)", value: "explore" },
          { label: "Discover (Find hidden targets)", value: "discover" },
        ],
      },
      {
        name: "maxClicks",
        label: "Max Clicks (Discover mode)",
        type: "number",
        required: false,
        defaultValue: 8,
        min: 1,
        max: 50,
      },
      {
        name: "markingMode",
        label: "Marking Mode (Discover mode)",
        type: "select",
        required: false,
        defaultValue: "self-mark",
        options: [
          { label: "Self Mark (Auto)", value: "self-mark" },
          { label: "Tutor Mark (Manual)", value: "tutor-mark" },
        ],
      },
      {
        name: "showNumbers",
        label: "Show Pin Numbers in Explore Mode",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 5,
        max: 300,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
    ],
  },

  // Gamified Components
  {
    type: "poll",
    label: "Poll",
    category: "interactive",
    description: "Interactive opinion poll with live response tallies and animated percentage bars.",
    icon: "📊",
    defaultProps: {
      question: "Which state of matter has a fixed shape and volume?",
      options: [
        { id: "opt1", text: "Solid" },
        { id: "opt2", text: "Liquid" },
        { id: "opt3", text: "Gas" },
        { id: "opt4", text: "Plasma" },
      ],
      points: 5,
      mode: "practice",
      state: "active",
      timeLimit: 10,
    },
    propDefinitions: [
      {
        name: "question",
        label: "Poll Question",
        type: "string",
        required: true,
        defaultValue: "Which state of matter has a fixed shape and volume?",
      },
      {
        name: "options",
        label: "Poll Options",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "opt1", text: "Solid" },
          { id: "opt2", text: "Liquid" },
          { id: "opt3", text: "Gas" },
          { id: "opt4", text: "Plasma" },
        ],
      },
      {
        name: "points",
        label: "Participation Points",
        type: "number",
        required: false,
        defaultValue: 5,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 5,
        max: 300,
      },
    ],
  },
  {
    type: "flashcardQuiz",
    label: "Flashcard Quiz",
    category: "interactive",
    description: "Multi-question quiz where the question flips onto a card, then answer options flip in sequentially for the student to pick.",
    icon: "🎴",
    defaultProps: {
      title: "Flashcard Quiz",
      questions: [
        {
          id: "fq1",
          question: "What is the capital of France?",
          options: ["Paris", "London", "Berlin", "Madrid"],
          correctAnswer: 0,
        },
        {
          id: "fq2",
          question: "What is 7 × 8?",
          options: ["54", "56", "63", "64"],
          correctAnswer: 1,
        },
      ],
      points: 20,
      mode: "practice",
      state: "active",
      timeLimit: 15,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Flashcard Quiz",
      },
      {
        name: "questions",
        label: "Questions",
        type: "componentArray",
        required: true,
        defaultValue: [
          {
            id: "fq1",
            question: "What is the capital of France?",
            options: ["Paris", "London", "Berlin", "Madrid"],
            correctAnswer: 0,
          },
        ],
      },
      {
        name: "points",
        label: "Total Points",
        type: "number",
        required: false,
        defaultValue: 20,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice", value: "practice" },
          { label: "Live", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 5,
        max: 300,
      },
    ],
  },
  {
    type: "spinTheWheel",
    label: "Spin the Wheel",
    category: "interactive",
    description: "Gamified wheel quiz engine. Students spin the wheel to unlock dynamic questions with required spin tracking.",
    icon: "🎡",
    defaultProps: {
      title: "Spin the Wheel Quiz",
      requiredSpins: 3,
      points: 20,
      mode: "practice",
      state: "active",
      questions: DEFAULT_WHEEL_QUESTIONS,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Spin the Wheel Quiz",
      },
      {
        name: "requiredSpins",
        label: "Required Spins",
        type: "number",
        required: false,
        defaultValue: 3,
        min: 1,
        max: 20,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 20,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice", value: "practice" },
          { label: "Live", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
    ],
  },
  {
    type: "multiSelectQuiz",
    label: "Multi-Select Quiz",
    category: "interactive",
    description: "Quiz where students select ALL correct answers from colorful option cards, with partial-score feedback.",
    icon: "☑️",
    defaultProps: {
      title: "Select All That Apply",
      questions: [
        {
          id: "q1",
          question: "Which of the following are mammals?",
          options: [
            { id: "a", text: "Dog", isCorrect: true, color: "bg-violet-500" },
            { id: "b", text: "Eagle", isCorrect: false, color: "bg-amber-500" },
            { id: "c", text: "Whale", isCorrect: true, color: "bg-sky-500" },
            { id: "d", text: "Salmon", isCorrect: false, color: "bg-rose-500" },
          ],
        },
      ],
      points: 15,
      mode: "practice",
      state: "active",
      timeLimit: 15,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Quiz Title",
        type: "string",
        required: false,
        defaultValue: "Select All That Apply",
      },
      {
        name: "questions",
        label: "Questions",
        type: "componentArray",
        required: true,
        defaultValue: [],
      },
      {
        name: "points",
        label: "Total Points",
        type: "number",
        required: false,
        defaultValue: 15,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice", value: "practice" },
          { label: "Live", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 5,
        max: 300,
      },
    ],
  },

  {
    type: "annotateImage",
    label: "Annotate Image",
    category: "interactive",
    description: "Label image diagram regions by placing target annotation tags.",
    icon: "🏷️",
    defaultProps: {
      title: "Label the Diagram",
      image: "/placeholder.svg?height=400&width=600",
      labels: [
        { id: "l1", text: "Nucleus", x: 0.5, y: 0.4 },
        { id: "l2", text: "Mitochondria", x: 0.2, y: 0.7 },
      ],
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Label the Diagram",
      },
      {
        name: "image",
        label: "Diagram Image URL",
        type: "image",
        required: true,
        defaultValue: "/placeholder.svg?height=400&width=600",
      },
      {
        name: "labels",
        label: "Annotation Targets",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "l1", text: "Nucleus", x: 0.5, y: 0.4 },
          { id: "l2", text: "Mitochondria", x: 0.2, y: 0.7 },
        ],
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 15,
      },
    ],
  },
  {
    type: "categorise",
    label: "Categorise",
    category: "interactive",
    description: "Sort items into designated category buckets or columns.",
    icon: "🗂️",
    defaultProps: {
      title: "Categorise the Items",
      categories: [
        { id: "c1", title: "Renewable Energy" },
        { id: "c2", title: "Non-Renewable Energy" },
      ],
      items: [
        { id: "i1", text: "Solar Power", categoryId: "c1" },
        { id: "i2", text: "Coal", categoryId: "c2" },
        { id: "i3", text: "Wind Turbines", categoryId: "c1" },
        { id: "i4", text: "Natural Gas", categoryId: "c2" },
      ],
      points: 20,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Categorise the Items",
      },
      {
        name: "categories",
        label: "Categories / Buckets",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "c1", title: "Category A" },
          { id: "c2", title: "Category B" },
        ],
      },
      {
        name: "items",
        label: "Items to Categorise",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "i1", text: "Item 1", categoryId: "c1" },
          { id: "i2", text: "Item 2", categoryId: "c2" },
        ],
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 20,
      },
    ],
  },
  {
    type: "timeline",
    label: "Timeline Rail",
    category: "interactive",
    description: "Interactive horizontal or vertical chronological event timeline.",
    icon: "⏳",
    defaultProps: {
      title: "Historical Timeline",
      events: [
        { id: "e1", year: "1969", title: "Moon Landing", description: "Apollo 11 mission touches down on the lunar surface." },
        { id: "e2", year: "1989", title: "World Wide Web", description: "Tim Berners-Lee proposes global hypertext system." },
        { id: "e3", year: "2007", title: "Smartphone Era", description: "First iPhone launches, revolutionizing mobile computing." },
      ],
      interactive: true,
      points: 15,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Historical Timeline",
      },
      {
        name: "events",
        label: "Timeline Events",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "e1", year: "1969", title: "Event 1", description: "Description 1" },
        ],
      },
      {
        name: "interactive",
        label: "Interactive Order Check",
        type: "boolean",
        required: false,
        defaultValue: true,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 15,
      },
    ],
  },

  {
    type: "annotationBoard",
    label: "Annotation Board",
    category: "gamified",
    description: "Subject-agnostic text tagging passage canvas with customizable label palette.",
    icon: "🏷️",
    defaultProps: {
      title: "Identify Grammar Roles",
      passage: "The quick brown fox jumps over the lazy dog.",
      labels: [
        { id: "l1", name: "Subject", color: "#1CB0F6" },
        { id: "l2", name: "Predicate Verb", color: "#58CC02" },
        { id: "l3", name: "Direct Object", color: "#FFC800" },
      ],
      correctAnswers: [
        { wordIndex: 2, labelId: "l1" },
        { wordIndex: 4, labelId: "l2" },
        { wordIndex: 8, labelId: "l3" },
      ],
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      { name: "title", label: "Title", type: "string", required: false, defaultValue: "Identify Grammar Roles" },
      { name: "passage", label: "Passage Text", type: "richText", required: true, defaultValue: "The quick brown fox jumps over the lazy dog." },
      { name: "labels", label: "Tag Categories Palette", type: "componentArray", required: true, defaultValue: [] },
      { name: "correctAnswers", label: "Target Tag Answers", type: "componentArray", required: true, defaultValue: [] },
      { name: "points", label: "Points", type: "number", required: false, defaultValue: 15 },
    ],
  },
  {
    type: "anagram",
    label: "Anagram Engine",
    category: "gamified",
    description: "Interactive scrambled letter tiles with hint system and shuffle pool.",
    icon: "🧩",
    defaultProps: {
      title: "Solve the Anagram",
      word: "ALGORITHM",
      hint: "A step-by-step set of instructions for solving a problem",
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      { name: "title", label: "Title", type: "string", required: false, defaultValue: "Solve the Anagram" },
      { name: "word", label: "Target Word", type: "string", required: true, defaultValue: "ALGORITHM" },
      { name: "hint", label: "Hint Text", type: "string", required: false, defaultValue: "" },
      { name: "points", label: "Points", type: "number", required: false, defaultValue: 15 },
    ],
  },
  {
    type: "hangman",
    label: "Word Quest (Hangman)",
    category: "gamified",
    description: "Gamified secret word guessing with A-Z virtual keyboard and 3D visual themes.",
    icon: "🔤",
    defaultProps: {
      title: "Word Quest Challenge",
      word: "ASTRONOMY",
      category: "Space Science",
      clue: "The scientific study of celestial bodies",
      theme: "spaceship",
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      { name: "title", label: "Title", type: "string", required: false, defaultValue: "Word Quest Challenge" },
      { name: "word", label: "Target Word", type: "string", required: true, defaultValue: "ASTRONOMY" },
      { name: "category", label: "Category Header", type: "string", required: false, defaultValue: "Space Science" },
      { name: "clue", label: "Clue Text", type: "string", required: false, defaultValue: "" },
      { name: "theme", label: "Visual Theme", type: "select", required: false, defaultValue: "spaceship", options: [{ label: "Spaceship Launch", value: "spaceship" }, { label: "Castle Siege", value: "castle" }, { label: "Classic Hearts", value: "classic" }] },
      { name: "points", label: "Points", type: "number", required: false, defaultValue: 15 },
    ],
  },
  {
    type: "swipeDeck",
    label: "Swipe Deck",
    category: "gamified",
    description: "Generic binary choice card deck with 3D tactile buttons and flippable explanations.",
    icon: "🎴",
    defaultProps: {
      title: "Myth vs Fact Challenge",
      leftLabel: "Myth",
      rightLabel: "Fact",
      cards: [
        { id: "c1", text: "Humans only use 10% of their brain.", correctSide: "left", explanation: "Brain imaging shows virtually all parts of the brain are active." },
        { id: "c2", text: "Water expands when it freezes.", correctSide: "right", explanation: "Ice forms a crystalline structure that occupies more volume." },
      ],
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      { name: "title", label: "Title", type: "string", required: false, defaultValue: "Myth vs Fact Challenge" },
      { name: "leftLabel", label: "Left Choice Label", type: "string", required: true, defaultValue: "Myth" },
      { name: "rightLabel", label: "Right Choice Label", type: "string", required: true, defaultValue: "Fact" },
      { name: "cards", label: "Deck Cards", type: "componentArray", required: true, defaultValue: [] },
      { name: "points", label: "Points", type: "number", required: false, defaultValue: 15 },
    ],
  },
  {
    type: "crossword",
    label: "Mini Crossword",
    category: "gamified",
    description: "Interactive 5x5 crossword grid with Across/Down clue navigation.",
    icon: "🗺️",
    defaultProps: {
      title: "Biology Key Terms Crossword",
      gridSize: { rows: 5, cols: 5 },
      words: [
        { id: "w1", word: "CELL", clue: "Basic unit of life", direction: "across", row: 1, col: 0 },
        { id: "w2", word: "DNA", clue: "Genetic code molecule", direction: "down", row: 0, col: 1 },
      ],
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      { name: "title", label: "Title", type: "string", required: false, defaultValue: "Mini Crossword" },
      { name: "gridSize", label: "Grid Size", type: "componentArray", required: true, defaultValue: { rows: 5, cols: 5 } },
      { name: "words", label: "Crossword Words", type: "componentArray", required: true, defaultValue: [] },
      { name: "points", label: "Points", type: "number", required: false, defaultValue: 15 },
    ],
  },
  {
    type: "spectrumSorter",
    label: "Spectrum Sorter",
    category: "gamified",
    description: "Continuous linear axis track for ordering items along a scale.",
    icon: "🎚️",
    defaultProps: {
      title: "pH Scale Spectrum Sorter",
      minLabel: "Acidic (pH 0)",
      maxLabel: "Alkaline (pH 14)",
      tolerance: 10,
      items: [
        { id: "i1", text: "Lemon Juice", correctPosition: 15 },
        { id: "i2", text: "Pure Water", correctPosition: 50 },
        { id: "i3", text: "Bleach", correctPosition: 90 },
      ],
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      { name: "title", label: "Title", type: "string", required: false, defaultValue: "Spectrum Sorter" },
      { name: "minLabel", label: "Min Bound Label", type: "string", required: true, defaultValue: "Low" },
      { name: "maxLabel", label: "Max Bound Label", type: "string", required: true, defaultValue: "High" },
      { name: "tolerance", label: "Accuracy Tolerance %", type: "number", required: false, defaultValue: 10 },
      { name: "items", label: "Spectrum Items", type: "componentArray", required: true, defaultValue: [] },
      { name: "points", label: "Points", type: "number", required: false, defaultValue: 15 },
    ],
  },
  {
    type: "jigsaw",
    label: "Jigsaw Diagram Puzzle",
    category: "gamified",
    description: "Interactive sliced image puzzle with drag-snap assembly and hotspot unlocks.",
    icon: "🧩",
    defaultProps: {
      title: "Assemble Cell Structure Diagram",
      image: "/placeholder.svg?height=400&width=600",
      gridSize: { rows: 3, cols: 3 },
      points: 20,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      { name: "title", label: "Title", type: "string", required: false, defaultValue: "Jigsaw Diagram Puzzle" },
      { name: "image", label: "Diagram Image", type: "image", required: true, defaultValue: "/placeholder.svg?height=400&width=600" },
      { name: "gridSize", label: "Grid Layout", type: "componentArray", required: true, defaultValue: { rows: 3, cols: 3 } },
      { name: "points", label: "Points", type: "number", required: false, defaultValue: 20 },
    ],
  },
  {
    type: "wordScramble",
    label: "Word & Sentence Rearrange",
    category: "gamified",
    description: "Tap scrambled tiles in order to unscramble words or build full sentences.",
    icon: "🔤",
    defaultProps: {
      title: "Unscramble the Sequence",
      variant: "single",
      word: "PHOTOSYNTHESIS",
      words: ["SOLAR", "SYSTEM"],
      sentence: "Photosynthesis converts sunlight into chemical energy.",
      hint: "Process used by plants to synthesize food from sunlight",
      allowTextClue: true,
      allowLetterReveal: true,
      maxLetterReveals: 3,
      allowWordSolve: true,
      maxWordSolves: 1,
      allowFirstLetterAnchors: true,
      points: 15,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "word",
        label: "Word Scramble Configuration",
        type: "componentArray",
        required: false,
        defaultValue: "PHOTOSYNTHESIS",
        description: "Configure variant (single/multi/sentence), target words, sentence, and hint.",
      },
      { name: "points", label: "Points", type: "number", required: false, defaultValue: 15 },
    ],
  },
  {
    type: "memoryGrid",
    label: "Memory Grid",
    category: "gamified",
    description: "Concentration memory game — flip cards to find matching pairs.",
    icon: "🎴",
    defaultProps: {
      title: "Memory Card Pairs",
      pairs: [
        { id: "p1", term: "Photosynthesis", definition: "Plants convert light to energy" },
        { id: "p2", term: "Respiration", definition: "Cells release energy from glucose" },
        { id: "p3", term: "Osmosis", definition: "Diffusion of water across a membrane" },
      ],
      points: 20,
      mode: "practice",
      state: "active",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Memory Card Pairs",
      },
      {
        name: "pairs",
        label: "Matching Pairs",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "p1", term: "Term 1", definition: "Definition 1" },
          { id: "p2", term: "Term 2", definition: "Definition 2" },
        ],
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 20,
      },
    ],
  },
  {
    type: "wordCloud",
    label: "Word Cloud",
    category: "interactive",
    description: "Live interactive word cloud canvas for brainstorming and keyword collection.",
    icon: "☁️",
    defaultProps: {
      title: "Live Word Cloud",
      question: "Type key terms or words related to today's topic:",
      placeholder: "Type a word...",
      maxWords: 30,
      points: 10,
      mode: "practice",
      state: "active",
      timeLimit: 20,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Live Word Cloud",
      },
      {
        name: "question",
        label: "Question Prompt",
        type: "string",
        required: true,
        defaultValue: "Type key terms or words related to today's topic:",
      },
      {
        name: "placeholder",
        label: "Placeholder Text",
        type: "string",
        required: false,
        defaultValue: "Type a word...",
      },
      {
        name: "maxWords",
        label: "Max Submitted Words",
        type: "number",
        required: false,
        defaultValue: 30,
        min: 5,
        max: 100,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 20,
        min: 5,
        max: 300,
      },
    ],
  },
  {
    type: "scaleSlider",
    label: "Scale Slider",
    category: "interactive",
    description: "Opinion spectrum slider for confidence ratings and agreement levels.",
    icon: "🎚️",
    defaultProps: {
      title: "Opinion Spectrum",
      prompt: "Rate your level of agreement or confidence:",
      minLabel: "Strongly Disagree",
      maxLabel: "Strongly Agree",
      min: 1,
      max: 10,
      step: 1,
      defaultValue: 5,
      points: 10,
      mode: "practice",
      state: "active",
      timeLimit: 15,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Opinion Spectrum",
      },
      {
        name: "prompt",
        label: "Prompt Text",
        type: "string",
        required: true,
        defaultValue: "Rate your level of agreement or confidence:",
      },
      {
        name: "minLabel",
        label: "Minimum Bound Label",
        type: "string",
        required: false,
        defaultValue: "Strongly Disagree",
      },
      {
        name: "maxLabel",
        label: "Maximum Bound Label",
        type: "string",
        required: false,
        defaultValue: "Strongly Agree",
      },
      {
        name: "min",
        label: "Minimum Value",
        type: "number",
        required: false,
        defaultValue: 1,
      },
      {
        name: "max",
        label: "Maximum Value",
        type: "number",
        required: false,
        defaultValue: 10,
      },
      {
        name: "step",
        label: "Step Increment",
        type: "number",
        required: false,
        defaultValue: 1,
      },
      {
        name: "defaultValue",
        label: "Default Value",
        type: "number",
        required: false,
        defaultValue: 5,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 5,
        max: 300,
      },
    ],
  },

  // Structure Components
  {
    type: "slideTitle",
    label: "Slide Title",
    category: "structure",
    description: "Main slide heading...",
    icon: "📑",
    defaultProps: {
      content: "Slide Title",
      align: "center",
      color: "black",
      backgroundColor: "transparent",
    },
    propDefinitions: [
      {
        name: "content",
        label: "Title Content",
        type: "string",
        required: true,
        defaultValue: "Slide Title",
      },
      {
        name: "align",
        label: "Text Alignment",
        type: "select",
        required: false,
        defaultValue: "center",
        options: [
          { label: "Left", value: "left" },
          { label: "Center", value: "center" },
          { label: "Right", value: "right" },
        ],
      },
      {
        name: "color",
        label: "Text Color",
        type: "color",
        required: false,
        defaultValue: "black",
      },
      {
        name: "backgroundColor",
        label: "Background Color",
        type: "color",
        required: false,
        defaultValue: "transparent",
      },
    ],
  },
]
