import type { ComponentDefinition } from "@/types/lesson"

export const hotspotDefinition: ComponentDefinition = {
    type: "hotspot",
    label: "Hotspot",
    category: "interactive",
    description: "Clickable image regions...",
    icon: "🎯",
    defaultProps: {
      title: "Interactive Image",
      image: "/placeholder.svg?height=400&width=600",
      hotspots: [
        { id: "1", x: 0.3, y: 0.4, label: "Point 1", content: "This is the first point of interest" },
        { id: "2", x: 0.7, y: 0.6, label: "Point 2", content: "This is the second point of interest" },
      ],
      points: 10,
      timeLimit: 15,
      mode: "practice",
      state: "active",
      behavior: "discover",
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Interactive Image",
      },
      {
        name: "image",
        label: "Image",
        type: "image",
        required: true,
        defaultValue: "/placeholder.svg?height=400&width=600",
      },
      {
        name: "hotspots",
        label: "Hotspots",
        type: "componentArray",
        required: true,
        defaultValue: [
          { id: "1", x: 0.3, y: 0.4, label: "Point 1", content: "This is the first point of interest" },
          { id: "2", x: 0.7, y: 0.6, label: "Point 2", content: "This is the second point of interest" },
        ],
      },
      {
        name: "behavior",
        label: "Interaction Behavior",
        type: "select",
        required: true,
        defaultValue: "discover",
        options: [
          { label: "Explore (Information only)", value: "explore" },
          { label: "Discover (Find hidden targets)", value: "discover" },
        ],
      },
      {
        name: "maxClicks",
        label: "Max Clicks (Discover mode)",
        type: "number",
        required: false,
        defaultValue: 8,
        min: 1,
        max: 50,
      },
      {
        name: "markingMode",
        label: "Marking Mode (Discover mode)",
        type: "select",
        required: false,
        defaultValue: "self-mark",
        options: [
          { label: "Self Mark (Auto)", value: "self-mark" },
          { label: "Tutor Mark (Manual)", value: "tutor-mark" },
        ],
      },
      {
        name: "showNumbers",
        label: "Show Pin Numbers in Explore Mode",
        type: "boolean",
        required: false,
        defaultValue: false,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 5,
        max: 300,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
    ],
  }
