import type { ComponentDefinition } from "@/types/lesson"

export const scaleSliderDefinition: ComponentDefinition = {
    type: "scaleSlider",
    label: "Scale Slider",
    category: "interactive",
    description: "Opinion spectrum slider for confidence ratings and agreement levels.",
    icon: "🎚️",
    defaultProps: {
      title: "Opinion Spectrum",
      prompt: "Rate your level of agreement or confidence:",
      minLabel: "Strongly Disagree",
      maxLabel: "Strongly Agree",
      min: 1,
      max: 10,
      step: 1,
      defaultValue: 5,
      points: 10,
      mode: "practice",
      state: "active",
      timeLimit: 15,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Opinion Spectrum",
      },
      {
        name: "prompt",
        label: "Prompt Text",
        type: "string",
        required: true,
        defaultValue: "Rate your level of agreement or confidence:",
      },
      {
        name: "minLabel",
        label: "Minimum Bound Label",
        type: "string",
        required: false,
        defaultValue: "Strongly Disagree",
      },
      {
        name: "maxLabel",
        label: "Maximum Bound Label",
        type: "string",
        required: false,
        defaultValue: "Strongly Agree",
      },
      {
        name: "min",
        label: "Minimum Value",
        type: "number",
        required: false,
        defaultValue: 1,
      },
      {
        name: "max",
        label: "Maximum Value",
        type: "number",
        required: false,
        defaultValue: 10,
      },
      {
        name: "step",
        label: "Step Increment",
        type: "number",
        required: false,
        defaultValue: 1,
      },
      {
        name: "defaultValue",
        label: "Default Value",
        type: "number",
        required: false,
        defaultValue: 5,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 15,
        min: 5,
        max: 300,
      },
    ],
  }
