import type { ComponentDefinition } from "@/types/lesson"

export const shortAnswerDefinition: ComponentDefinition = {
    type: "shortAnswer",
    label: "Short Answer",
    category: "interactive",
    description: "Open-ended question with free-text response, keywords check, or tutor marking.",
    icon: "✍️",
    defaultProps: {
      title: "Short Answer",
      question: "Explain why ecosystems depend on primary producers:",
      placeholder: "Write your answer here...",
      correctKeywords: ["energy", "photosynthesis", "food chain"],
      markingMode: "self-mark",
      points: 10,
      mode: "practice",
      state: "active",
      timeLimit: 30,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Short Answer",
      },
      {
        name: "question",
        label: "Question Prompt",
        type: "string",
        required: true,
        defaultValue: "Explain why ecosystems depend on primary producers:",
      },
      {
        name: "placeholder",
        label: "Placeholder Text",
        type: "string",
        required: false,
        defaultValue: "Write your answer here...",
      },
      {
        name: "markingMode",
        label: "Marking Mode",
        type: "select",
        required: false,
        defaultValue: "self-mark",
        options: [
          { label: "Self Mark (Keyword Check)", value: "self-mark" },
          { label: "Tutor Mark (Manual)", value: "tutor-mark" },
        ],
      },
      {
        name: "correctKeywords",
        label: "Required Keywords (Self-Mark)",
        type: "json",
        required: false,
        defaultValue: ["energy", "photosynthesis", "food chain"],
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        required: false,
        defaultValue: "practice",
        options: [
          { label: "Practice Mode", value: "practice" },
          { label: "Live Mode", value: "live" },
        ],
      },
      {
        name: "state",
        label: "State",
        type: "select",
        required: false,
        defaultValue: "active",
        options: [
          { label: "Active", value: "active" },
          { label: "Disabled", value: "disabled" },
        ],
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 30,
        min: 5,
        max: 300,
      },
    ],
  }
