import type { ComponentDefinition } from "@/types/lesson"

export const wordCloudDefinition: ComponentDefinition = {
    type: "wordCloud",
    label: "Word Cloud",
    category: "interactive",
    description: "Live interactive word cloud canvas for brainstorming and keyword collection.",
    icon: "☁️",
    defaultProps: {
      title: "Live Word Cloud",
      question: "Type key terms or words related to today's topic:",
      placeholder: "Type a word...",
      maxWords: 30,
      points: 10,
      mode: "practice",
      state: "active",
      timeLimit: 20,
    },
    propDefinitions: [
      {
        name: "title",
        label: "Title",
        type: "string",
        required: false,
        defaultValue: "Live Word Cloud",
      },
      {
        name: "question",
        label: "Question Prompt",
        type: "string",
        required: true,
        defaultValue: "Type key terms or words related to today's topic:",
      },
      {
        name: "placeholder",
        label: "Placeholder Text",
        type: "string",
        required: false,
        defaultValue: "Type a word...",
      },
      {
        name: "maxWords",
        label: "Max Submitted Words",
        type: "number",
        required: false,
        defaultValue: 30,
        min: 5,
        max: 100,
      },
      {
        name: "points",
        label: "Points",
        type: "number",
        required: false,
        defaultValue: 10,
        min: 0,
        max: 100,
      },
      {
        name: "timeLimit",
        label: "Time Limit (Seconds)",
        type: "number",
        required: false,
        defaultValue: 20,
        min: 5,
        max: 300,
      },
    ],
  }
