import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (relative: string) => readFileSync(join(process.cwd(), relative), 'utf8')

describe('W5 store and login streak', () => {
    it('exposes a student star store and live powerup bar', () => {
        expect(read('app/dashboard/student/store/page.tsx')).toContain('Star market')
        expect(read('app/dashboard/student/store/page.tsx')).toContain('resetLesson')
        expect(read('app/dashboard/student/store/page.tsx')).toContain('Choose a lesson')
        expect(read('app/dashboard/student/store/page.tsx')).not.toContain('Lesson id')
        expect(read('lib/api-client.ts')).toContain('listMine')
        expect(read('components/store/live-powerup-bar.tsx')).toContain('live_time')
        expect(read('components/store/live-powerup-bar.tsx')).toContain('owned.length === 0')
        expect(read('components/live-mode.tsx')).toContain('LivePowerupBar')
        expect(read('components/live-mode.tsx')).toContain('useLivePowerups')
        expect(read('app/dashboard/student/store/page.tsx')).toContain('variant="duo"')
        expect(read('lib/api-client.ts')).toContain("this.post('/store/buy'")
        expect(read('lib/api-client.ts')).toContain('printCertificate')
        expect(read('lib/api-client.ts')).toContain("this.post('/store/consume'")
        expect(read('lib/api-client.ts')).toContain("this.post('/store/reset-block'")
        expect(read('lib/api-client.ts')).toContain("this.post('/store/open-reference'")
        expect(read('lib/api-client.ts')).toContain("this.post('/store/unlock-lesson'")
        expect(read('lib/store-skus.ts')).toContain('LESSON_EARLY_UNLOCK_COST = 20')
        expect(read('app/dashboard/student/store/page.tsx')).toContain('Consumables')
        expect(read('app/dashboard/student/store/page.tsx')).toContain('Cosmetics')
        expect(read('lib/certificates.ts')).toContain('CERTIFICATE_PRINT_COST = 5')
        expect(read('lib/certificates.ts')).toContain('CERT_WIDTH = 1600')
        expect(read('lib/store-skus.ts')).toContain('BLOCK_RESET_ON_DEMAND_COST = 15')
        expect(read('lib/store-skus.ts')).toContain('REFERENCE_ON_DEMAND_COST = 15')
        expect(read('lib/store-skus.ts')).toContain('BLOCK_RESET_STORE_COST = 10')
        expect(read('lib/certificates.ts')).toContain('drawAstMascot')
        expect(read('lib/certificates.ts')).toContain('/icons/icon-512x512.png')
        expect(read('lib/pride-card-themes.ts')).toContain('loginStreak')
        expect(read('lib/ast-mascot.ts')).toContain("impression === 'cool'")
        expect(read('components/certificates/certificate-studio.tsx')).toContain('Download PDF')
        expect(read('components/certificates/certificate-studio.tsx')).toContain('Preview of what you get')
        expect(read('components/viewer/LessonCompletionOverlay.tsx')).toContain('Print certificate')
        expect(read('app/dashboard/student/pride/[statKey]/page.tsx')).toContain('Print pride certificate')
        expect(read('components/dashboard/sidebar/student-sidebar.tsx')).toContain('/dashboard/student/store')
    })

    it('shows a dramatic login streak and a pride board for it', () => {
        expect(read('components/store/login-streak-modal.tsx')).toContain('Day streak')
        expect(read('components/store/login-streak-modal.tsx')).toContain('streakModalStorageKey')
        expect(read('lib/streak.ts')).toContain('ast-streak-modal')
        expect(read('app/dashboard/student/layout.tsx')).toContain('LoginStreakModal')
        expect(read('app/dashboard/student/page.tsx')).toContain('StudentEconomyPanels')
        expect(read('app/dashboard/student/page.tsx')).not.toContain('min-w-[7.5rem]')
        expect(read('components/dashboard/student/economy-panels.tsx')).toContain('/dashboard/student/streak')
        expect(read('components/dashboard/student/economy-panels.tsx')).toContain('/dashboard/student/store')
        expect(read('components/dashboard/student/economy-panels.tsx')).toContain('How to earn')
        expect(read('components/dashboard/student/economy-panels.tsx')).toContain('evaluateLevelTimeline')
        expect(read('app/dashboard/student/streak/page.tsx')).toContain('Milestone stars')
        expect(read('lib/streak.ts')).toContain('5 * (2 ** index)')
        expect(read('lib/streak.ts')).toContain('streakHeat')
        expect(read('components/store/login-streak-modal.tsx')).toContain('Claim +')
        expect(read('lib/sound-effects.ts')).toContain('starsSpent')
        expect(read('context/gamification-context.tsx')).toContain('loginStreak')
    })

    it('wires remaining store, reference, cosmetics, and tutor-mark surfaces', () => {
        expect(read('hooks/use-hint-pack.ts')).toContain("sku: 'hint_pack'")
        expect(read('components/renderers/anagram-renderer.tsx')).toContain('useHintPack')
        expect(read('components/renderers/word-scramble-renderer.tsx')).toContain('useHintPack')
        expect(read('components/store/live-block-reset.tsx')).toContain('resetBlock')
        expect(read('components/reference/reference-chip.tsx')).toContain('Open reference')
        expect(read('components/lesson-builder.tsx')).toContain('referenceOptions')
        expect(read('components/component-editor.tsx')).toContain('ReferenceProvider')
        expect(read('components/component-renderer.tsx')).toContain('ReferenceChip')
        expect(read('app/dashboard/student/settings/page.tsx')).toContain('Gold frame')
        expect(read('components/pride/handle-avatar.tsx')).toContain("avatarFrame === 'gold'")
        expect(read('components/renderers/fill-in-the-blank-renderer.tsx')).toContain("status: 'pending'")
        expect(read('domain/component-status.ts')).toContain('isPendingMarking')
        expect(read('components/viewer/TutorLessonContent.tsx')).toContain("'hotspot'")
        expect(read('components/viewer/TutorLessonContent.tsx')).toContain('assignments')
        expect(read('lib/api-client.ts')).toContain('type?: string')
        expect(read('components/pride/gold-hint.tsx')).not.toContain('shrink-0">Gold</span>')
    })
})
